# Generated by Django 6.0.4 on 2026-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
