# Generated by Django 6.0.4 on 2026-04-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0003_dataplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
