# Generated by Django 6.0.4 on 2026-04-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0006_biometriccredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriccredential',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='biometriccredential',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
