# Generated by Django 6.0.4 on 2026-05-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0008_remove_biometriccredential_email_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataplan',
            name='smeplug_plan_id',
            field=models.CharField(blank=True, help_text='Plan ID from Smeplug API', max_length=100, null=True),
        ),
    ]
