# Generated by Django 6.0.4 on 2026-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0009_dataplan_smeplug_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataplan',
            name='network_id',
            field=models.IntegerField(default=1, help_text='1=MTN, 2=Airtel, 3=9mobile, 4=Glo'),
        ),
        migrations.AlterField(
            model_name='dataplan',
            name='smeplug_plan_id',
            field=models.CharField(blank=True, help_text='Plan ID from Smeplug (e.g: 1, AIR1000, 9MOB500)', max_length=50, null=True),
        ),
    ]
