# Generated by Django 6.0.4 on 2026-05-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0013_transaction_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gafia_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gafia_account_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gafia_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
