# Generated by Django 6.0.4 on 2026-05-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0014_profile_gafia_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
