# Generated by Django 6.0.4 on 2026-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0015_transaction_transaction_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_pin',
        ),
        migrations.AddField(
            model_name='profile',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
