# Generated by Django 6.0.4 on 2026-05-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0018_alter_profile_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataplan',
            name='plan_type',
            field=models.CharField(choices=[('SME', 'SME'), ('GIFTING', 'Gifting'), ('AWOOF', 'Awoof / Promo'), ('CORPORATE', 'Corporate Gifting')], default='SME', max_length=20),
        ),
    ]
